name: isar_test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl: ^0.20.2
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
  json_annotation: ^4.9.0
  meta: ^1.16.0
  path: ^1.9.1
  path_provider: ^2.1.5
  test: any

dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4

dependency_overrides:
  isar:
    path: ../isar
  isar_flutter_libs:
    path: ../isar_flutter_libs
